- hosts: all
  connection: local
  run_once: true
  vars:
    istioversion: "0.4.0"
  tasks:
  - name: Install istio
    shell: |
      mkdir -p ~/opt/istio
      cd ~/opt/istio
      
      ISTIO_VERSION=${ISTIO_VERSION:-{{ istioversion }}}
      NAME="istio-$ISTIO_VERSION"
      OSEXT="linux"
      URL="https://github.com/istio/istio/releases/download/${ISTIO_VERSION}/istio-${ISTIO_VERSION}-${OSEXT}.tar.gz"

      echo "Downloading $NAME from $URL ..."
      curl -L "$URL" | tar xz
      
      echo "Downloaded into $NAME:"
      ls $NAME
    args:
      creates: "~/opt/istio/istio-{{ istioversion }}"
  - name: Add istio to path in ~/.zshrc
    lineinfile:
      path: ~/.zshrc
      line: "export PATH=\"/home/fedora/opt/istio/istio-{{ istioversion }}/bin:$PATH\""
      regexp: "export PATH=.*/opt/istio/istio.*"
      state: present